name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run API tests
        run: npm run ci

      - name: Publish JUnit Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: API Tests
          path: test-results.xml
          reporter: jest-junit